package com.ombdev.inventorysystemapi.model;

public enum SortBy {
    ID_DESC,
    CATEGORY_CODE_ASC,
    CATEGORY_CODE_DESC,
    CATEGORY_NAME_ASC,
    CATEGORY_NAME_DESC,

    PRODUCT_NAME_ASC,
    PRODUCT_NAME_DESC,
    PRODUCT_CODE_ASC,
    PRODUCT_CODE_DESC,
    PRODUCT_PRICE_ASC,
    PRODUCT_PRICE_DESC,
    PRODUCT_QUANTITY_ASC,
    PRODUCT_QUANTITY_DESC,

}
